//at table level 

.alter  table Ternium_0 policy mirroring
 dataformat = parquet
 with (
  IsEnabled  = true,
 Backfill = false,
 TargetLatencyInMinutes = 5 //Delay can be adjusted between min 5 min to 3 hrs
 )

 //at database level

 .alter database [DatabaseName] policy mirroring 
dataformat = parquet 
with (
    IsEnabled = true,
    Backfill = false,
    TargetLatencyInMinutes = 5 //Delay can be adjusted between min 5 min to 3 hrs
)
